name: workflow-chain-5

on:

  workflow_dispatch:
    branches: [main]

  workflow_run:
    workflows: ["workflow-chain-4"]
    branches: [main]
    types:
      - completed

jobs:

  workflow-chain-5:
    runs-on: Ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: workflow-chain-5
      run:  echo workflow-chain-5
